name: lista_de_tarefas
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2

  #RXDART
  rxdart: ^0.27.7

  #Awesome_icons
  font_awesome_flutter: ^10.3.0

  #OBJECT_BOX
  objectbox: ^1.7.0
  objectbox_flutter_libs: any

  #CALENDAR
  table_calendar: ^3.0.8

  #DATE_FORMAT
  intl:

  #FIREBASE
  firebase_storage: ^11.0.8
  firebase_auth: ^4.2.1
  firebase_core: ^2.3.0
  cloud_firestore: ^4.0.5

  google_sign_in: ^5.4.2

  connectivity_plus: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  #OBJECT_BOX
  build_runner: ^2.0.0
  objectbox_generator: any

  flutter_lints: ^2.0.0

objectbox:
  output_dir: database

flutter:

  assets:
  - assets/images/

  uses-material-design: true

