name: lista_de_tarefas
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2

  #RXDART
  rxdart: ^0.27.7

  #Awesome_icons
  font_awesome_flutter: ^10.3.0

  #OBJECT_BOX
  objectbox: ^1.7.0
  objectbox_flutter_libs: any

  #CALENDAR
  table_calendar: ^3.0.8

  #DATE_FORMAT
  intl:

dev_dependencies:
  flutter_test:
    sdk: flutter

  #OBJECT_BOX
  build_runner: ^2.0.0
  objectbox_generator: any

  flutter_lints: ^2.0.0

objectbox:
  output_dir: database

flutter:

  uses-material-design: true

